plugins {
    id 'com.android.application'
}

android {
    namespace 'vn.svframe.bestiary.manager'
    compileSdk 35

    defaultConfig {
        applicationId 'vn.svframe.bestiary.manager'
        minSdk 26
        targetSdk 35
        versionCode 10000
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
