from pathlib import Path
import re

APP = Path('amethyst/app_pojavlauncher')
JAVA = APP / 'src/main/java/net/kdt/pojavlaunch'
RES = APP / 'src/main/res'


def req(ok, message):
    if not ok:
        raise SystemExit(message)


# ---------------------------------------------------------------------------
# Bestiary Android 1.0.6 - one consolidated performance patch.
# Applied directly after the functional 1.0.2 patch. Historical 1.0.4/1.0.5
# performance patches are intentionally not part of the final build chain.
# ---------------------------------------------------------------------------
build = APP / 'build.gradle'
s = build.read_text(encoding='utf-8')
req('versionName "1.0.2"' in s, '1.0.2 versionName marker missing')
s = s.replace('versionName "1.0.2"', 'versionName "1.0.6"', 1)
if 'versionCode 10000003' in s:
    s = s.replace('versionCode 10000003', 'versionCode 10000006', 1)
build.write_text(s, encoding='utf-8')


# ---------------------------------------------------------------------------
# 1) JVM policy: Java 21 ergonomics by default. Do not inject server/desktop G1
# recipes. Only exact strings generated by old Bestiary builds are migrated.
# ---------------------------------------------------------------------------
generator_java = r'''package net.kdt.pojavlaunch;

import android.content.Context;

public final class BestiaryJvmFlagGenerator {
    private static final String[] LEGACY_GENERATED = new String[] {
            "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -Dfile.encoding=UTF-8",
            "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:+UseStringDeduplication -Dfile.encoding=UTF-8",
            "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=75 -XX:G1ReservePercent=15 -XX:InitiatingHeapOccupancyPercent=30 -XX:+DisableExplicitGC -Dfile.encoding=UTF-8",
            "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=75 -XX:G1ReservePercent=15 -XX:InitiatingHeapOccupancyPercent=30 -XX:+DisableExplicitGC -XX:+UseStringDeduplication -Dfile.encoding=UTF-8"
    };

    private BestiaryJvmFlagGenerator() {}

    public static String generate(Context context) {
        return "";
    }

    public static boolean isLegacyGenerated(String args) {
        String normalized = normalize(args);
        if (normalized.isEmpty()) return false;
        for (String legacy : LEGACY_GENERATED) {
            if (legacy.equals(normalized)) return true;
        }
        return false;
    }

    private static String normalize(String value) {
        return value == null ? "" : value.trim().replaceAll("\\s+", " ");
    }
}
'''
(JAVA / 'BestiaryJvmFlagGenerator.java').write_text(generator_java, encoding='utf-8')


# ---------------------------------------------------------------------------
# 2) One Android performance profile. Heap is an Xmx budget, NOT Xms. Render
# resolution is a pixel budget. Experimental MobileGlues paths are opt-in.
# ---------------------------------------------------------------------------
profile_java = r'''package net.kdt.pojavlaunch;

import android.content.Context;
import android.content.SharedPreferences;
import android.util.DisplayMetrics;
import android.util.Log;

import net.kdt.pojavlaunch.prefs.LauncherPreferences;

public final class BestiaryPerformanceProfile {
    private static final String TAG = "BestiaryPerformance";
    private static final String REVISION_KEY = "bestiary_performance_revision";
    private static final String JVM_MODE_KEY = "bestiary_jvm_mode";
    private static final String VERBOSE_NATIVE_LOG_KEY = "bestiary_verbose_native_log";
    private static final int REVISION = 6;

    private BestiaryPerformanceProfile() {}

    public static void install(Context context) {
        SharedPreferences prefs = LauncherPreferences.DEFAULT_PREF;
        int previousRevision = prefs.getInt(REVISION_KEY, 0);
        if (previousRevision >= REVISION) return;

        int ram = Tools.getTotalDeviceMemory(context);
        int cores = Runtime.getRuntime().availableProcessors();
        DisplayMetrics dm = context.getResources().getDisplayMetrics();
        int minSide = Math.max(1, Math.min(dm.widthPixels, dm.heightPixels));

        String currentJavaArgs = prefs.getString("javaArgs", "");
        String currentJvmMode = prefs.getString(JVM_MODE_KEY, "");
        boolean legacyGeneratedJvm = BestiaryJvmFlagGenerator.isLegacyGenerated(currentJavaArgs);

        int targetHeap = defaultHeapMb(ram);
        int targetRatio = defaultResolutionRatio(ram, minSide);
        int currentHeap = prefs.getInt("allocation", -1);
        int currentRatio = prefs.getInt("resolutionRatio", -1);

        // Only migrate values when an older performance revision exists AND both
        // heap/resolution still match a Bestiary-generated pair. A 1.0.2 user who
        // manually changed settings has no performance revision and is preserved.
        boolean legacyManagedValues = previousRevision >= 2 && previousRevision < REVISION
                && isLegacyAutoHeap(currentHeap, ram)
                && isLegacyAutoRatio(currentRatio, ram, minSide);

        SharedPreferences.Editor edit = prefs.edit();
        boolean heapChanged = false;
        boolean ratioChanged = false;

        if (!prefs.contains("allocation")) {
            edit.putInt("allocation", targetHeap);
            currentHeap = targetHeap;
            heapChanged = true;
        } else if (legacyManagedValues && currentHeap != targetHeap) {
            edit.putInt("allocation", targetHeap);
            currentHeap = targetHeap;
            heapChanged = true;
        }

        if (!prefs.contains("resolutionRatio")) {
            edit.putInt("resolutionRatio", targetRatio);
            currentRatio = targetRatio;
            ratioChanged = true;
        } else if (legacyManagedValues && currentRatio != targetRatio) {
            edit.putInt("resolutionRatio", targetRatio);
            currentRatio = targetRatio;
            ratioChanged = true;
        }

        // Do not guess that thermal/scheduler overrides increase FPS. Android has
        // live scheduler and thermal information that a static launcher heuristic
        // does not. Users may still opt in manually after installation.
        if (!prefs.contains("sustainedPerformance")) edit.putBoolean("sustainedPerformance", false);
        if (!prefs.contains("bigCoreAffinity")) edit.putBoolean("bigCoreAffinity", false);
        if (previousRevision == 2 && legacyManagedValues) {
            if (cores >= 6 && prefs.getBoolean("sustainedPerformance", false)) {
                edit.putBoolean("sustainedPerformance", false);
            }
            if (cores >= 8 && prefs.getBoolean("bigCoreAffinity", false)) {
                edit.putBoolean("bigCoreAffinity", false);
            }
        }
        if (!prefs.contains("force_vsync")) edit.putBoolean("force_vsync", false);
        if (!prefs.contains("alternate_surface")) edit.putBoolean("alternate_surface", true);
        if (!prefs.contains(VERBOSE_NATIVE_LOG_KEY)) edit.putBoolean(VERBOSE_NATIVE_LOG_KEY, false);

        // MobileGlues conservative defaults. Direct/native GLES is preferred when
        // available; compute/DSA/multidraw-compute remain opt-in because they are
        // highly driver-sensitive on low-end Mali/Adreno devices.
        if (!prefs.contains("mg_renderer_setting_angle")) edit.putString("mg_renderer_setting_angle", "0");
        if (!prefs.contains("mg_renderer_setting_multidraw")) edit.putString("mg_renderer_setting_multidraw", "0");
        if (!prefs.contains("mg_renderer_setting_fsr")) edit.putString("mg_renderer_setting_fsr", "0");
        if (!prefs.contains("mg_renderer_setting_errorSetting")) edit.putString("mg_renderer_setting_errorSetting", "0");
        if (!prefs.contains("mg_renderer_setting_glsl_cache_size")) edit.putString("mg_renderer_setting_glsl_cache_size", "128");
        if (!prefs.contains("mg_renderer_computeShaderext")) edit.putBoolean("mg_renderer_computeShaderext", false);
        if (!prefs.contains("mg_renderer_dsaExt")) edit.putBoolean("mg_renderer_dsaExt", false);
        if (!prefs.contains("mg_renderer_multidrawCompute")) edit.putBoolean("mg_renderer_multidrawCompute", false);
        if (!prefs.contains("mg_renderer_setting_timerQueryExt")) edit.putBoolean("mg_renderer_setting_timerQueryExt", false);
        if (!prefs.contains("mg_renderer_setting_angleDepthClearFixMode")) edit.putBoolean("mg_renderer_setting_angleDepthClearFixMode", false);

        if (legacyGeneratedJvm) {
            edit.putString("javaArgs", "");
            edit.putString(JVM_MODE_KEY, "JAVA21_DEFAULTS");
            currentJvmMode = "JAVA21_DEFAULTS";
        } else {
            String trimmed = currentJavaArgs == null ? "" : currentJavaArgs.trim();
            currentJvmMode = trimmed.isEmpty() ? "JAVA21_DEFAULTS" : "CUSTOM";
            edit.putString(JVM_MODE_KEY, currentJvmMode);
        }

        edit.putInt(REVISION_KEY, REVISION).apply();
        Log.i(TAG, "revision=" + previousRevision + "->" + REVISION
                + " ramMb=" + ram + " cores=" + cores
                + " minSide=" + minSide + " xmxMb=" + currentHeap
                + " xmsMb=" + initialHeapMb(currentHeap)
                + " ratio=" + currentRatio + " targetShortSide=" + targetShortSide(ram)
                + " targetHz=" + targetRefreshRate()
                + " jvmMode=" + currentJvmMode
                + " legacyManaged=" + legacyManagedValues
                + " heapChanged=" + heapChanged + " ratioChanged=" + ratioChanged);
    }

    public static int initialHeapMb(int maxHeapMb) {
        if (maxHeapMb <= 768) return 128;
        if (maxHeapMb <= 1536) return 256;
        if (maxHeapMb <= 2304) return 384;
        return 512;
    }

    public static float targetRefreshRate() {
        return 60.0f;
    }

    public static boolean verboseNativeLoggingEnabled() {
        SharedPreferences prefs = LauncherPreferences.DEFAULT_PREF;
        return prefs != null && prefs.getBoolean(VERBOSE_NATIVE_LOG_KEY, false);
    }

    private static int defaultHeapMb(int ramMb) {
        if (ramMb >= 11000) return 3072;
        if (ramMb >= 7500) return 2560;
        if (ramMb >= 5500) return 2048;
        if (ramMb >= 3800) return 1536;
        if (ramMb >= 2800) return 1280;
        return 1024;
    }

    private static int targetShortSide(int ramMb) {
        if (ramMb < 2800) return 432;
        if (ramMb < 3800) return 480;
        if (ramMb < 5500) return 540;
        if (ramMb < 7500) return 600;
        if (ramMb < 11000) return 720;
        return 800;
    }

    private static int defaultResolutionRatio(int ramMb, int minSide) {
        int target = targetShortSide(ramMb);
        if (minSide <= target) return 100;
        int raw = (target * 100) / minSide;
        int ratio = (raw / 5) * 5;
        if (ratio < 25) ratio = 25;
        if (ratio > 100) ratio = 100;
        return ratio;
    }

    private static boolean isLegacyAutoHeap(int heap, int ramMb) {
        int v104 = ramMb >= 8192 ? 3072 : ramMb >= 6144 ? 2560 : ramMb >= 4096 ? 2048 : 1536;
        int current = defaultHeapMb(ramMb);
        return heap == v104 || heap == current;
    }

    private static boolean isLegacyAutoRatio(int ratio, int ramMb, int minSide) {
        int v104 = minSide >= 1440 ? 55 : minSide >= 1080 ? 65 : minSide >= 900 ? 75 : 85;
        return ratio == v104 || ratio == defaultResolutionRatio(ramMb, minSide);
    }
}
'''
(JAVA / 'BestiaryPerformanceProfile.java').write_text(profile_java, encoding='utf-8')


# Install profile before a second preference load so static preference fields use
# the new values immediately in both :launcher and :game processes.
app = JAVA / 'PojavApplication.java'
s = app.read_text(encoding='utf-8')
if 'BestiaryPerformanceProfile.install(this);' not in s:
    needle = '\t\t\t\tLauncherPreferences.loadPreferences(this);\n'
    req(needle in s, 'PojavApplication preference load marker missing')
    s = s.replace(needle, needle + '\t\t\t\tBestiaryPerformanceProfile.install(this);\n\t\t\t\tLauncherPreferences.loadPreferences(this);\n', 1)
app.write_text(s, encoding='utf-8')


# Keep renderer preference UI consistent with the conservative MobileGlues
# default used by the profile: "Disable ANGLE if possible" instead of enabling
# another translation layer by default.
pref_renderer = RES / 'xml/pref_renderer.xml'
x = pref_renderer.read_text(encoding='utf-8')
angle_block = '''            android:key="mg_renderer_setting_angle"
            android:defaultValue="1"'''
req(angle_block in x, 'MobileGlues ANGLE default marker missing')
x = x.replace(angle_block, '''            android:key="mg_renderer_setting_angle"
            android:defaultValue="0"''', 1)
pref_renderer.write_text(x, encoding='utf-8')


# Replace the old one-click generated-G1 button with an explicit reset to Java
# 21 defaults. RAM allocation remains controlled by the launcher memory slider.
pref_java = RES / 'xml/pref_java.xml'
x = pref_java.read_text(encoding='utf-8')
req('android:key="bestiary_generate_jvm_flags"' in x, 'Bestiary JVM preference missing')
x = x.replace('android:title="Tạo JVM flags tự động"', 'android:title="Khôi phục JVM mặc định"')
x = x.replace(
    'android:summary="Sinh bộ flag Java 21 an toàn theo RAM đã cấp. Không ghi đè giới hạn RAM."',
    'android:summary="Khuyên dùng trên Android: để Java 21 tự chọn GC/ergonomics. Xóa JVM flags tùy chỉnh nhưng không đổi RAM."'
)
pref_java.write_text(x, encoding='utf-8')

java_fragment = JAVA / 'prefs/screens/LauncherPreferenceJavaFragment.java'
s = java_fragment.read_text(encoding='utf-8')
old = '''        requirePreference("bestiary_generate_jvm_flags").setOnPreferenceClickListener(preference -> {
            String generated = BestiaryJvmFlagGenerator.generate(requireContext());
            LauncherPreferences.DEFAULT_PREF.edit().putString("javaArgs", generated).apply();
            LauncherPreferences.PREF_CUSTOM_JAVA_ARGS = generated;
            if (editJVMArgs != null) editJVMArgs.setText(generated);
            new androidx.appcompat.app.AlertDialog.Builder(requireContext())
                    .setTitle("JVM FLAGS ĐÃ TẠO")
                    .setMessage(generated)
                    .setPositiveButton("OK", null)
                    .show();
            return true;
        });'''
req(old in s, '1.0.2 JVM generator handler missing')
new = '''        requirePreference("bestiary_generate_jvm_flags").setOnPreferenceClickListener(preference -> {
            LauncherPreferences.DEFAULT_PREF.edit()
                    .putString("javaArgs", "")
                    .putString("bestiary_jvm_mode", "JAVA21_DEFAULTS")
                    .apply();
            LauncherPreferences.PREF_CUSTOM_JAVA_ARGS = "";
            if (editJVMArgs != null) editJVMArgs.setText("");
            new androidx.appcompat.app.AlertDialog.Builder(requireContext())
                    .setTitle("JVM MẶC ĐỊNH JAVA 21")
                    .setMessage("Đã xóa JVM flags tùy chỉnh. Bestiary dùng GC và JVM ergonomics mặc định của Java 21; giới hạn RAM giữ nguyên.")
                    .setPositiveButton("OK", null)
                    .show();
            return true;
        });'''
s = s.replace(old, new, 1)
java_fragment.write_text(s, encoding='utf-8')


# ---------------------------------------------------------------------------
# 3) JVM launch path. Upstream uses Xms == Xmx, immediately pressuring Android,
# renderer/native memory and textures. Xmx remains the user/auto budget, while
# Xms is small. Do not force ActiveProcessorCount; Java 21 can observe cpusets.
# Continuous logcat mirroring is also disabled by default.
# ---------------------------------------------------------------------------
jre = JAVA / 'utils/JREUtils.java'
j = jre.read_text(encoding='utf-8')
old = '''        //Add automatically generated args
        userArgs.add("-Xms" + LauncherPreferences.PREF_RAM_ALLOCATION + "M");
        userArgs.add("-Xmx" + LauncherPreferences.PREF_RAM_ALLOCATION + "M");'''
req(old in j, 'upstream Xms=Xmx marker missing')
new = '''        // Bestiary: allocation is an Xmx ceiling, not a request to commit the
        // whole heap at process start. Native renderer/driver memory needs room.
        int bestiaryMaxHeapMb = LauncherPreferences.PREF_RAM_ALLOCATION;
        int bestiaryInitialHeapMb = BestiaryPerformanceProfile.initialHeapMb(bestiaryMaxHeapMb);
        userArgs.add("-Xms" + bestiaryInitialHeapMb + "M");
        userArgs.add("-Xmx" + bestiaryMaxHeapMb + "M");
        Logger.appendToLog("Bestiary memory policy: Xms=" + bestiaryInitialHeapMb
                + "M Xmx=" + bestiaryMaxHeapMb + "M");'''
j = j.replace(old, new, 1)

# Remove both sides of the old forced processor-count policy. If a user enters a
# custom ActiveProcessorCount it is now treated like any other advanced JVM arg.
j = j.replace('        purgeArg(userArgs, "-XX:ActiveProcessorCount");\n', '', 1)
j = j.replace('        // Some phones are not using the right number of cores, fix that\n        userArgs.add("-XX:ActiveProcessorCount=" + java.lang.Runtime.getRuntime().availableProcessors());\n', '', 1)
j = j.replace('        System.out.println(JVMArgs);\n', '', 1)

redirect_marker = '''    public static void redirectAndPrintJRELog() {

        Log.v("jrelog","Log starts here");'''
req(redirect_marker in j, 'native logcat mirror marker missing')
j = j.replace(redirect_marker, '''    public static void redirectAndPrintJRELog() {
        if (!BestiaryPerformanceProfile.verboseNativeLoggingEnabled()) {
            Log.i("BestiaryPerformance", "Continuous native logcat mirror disabled");
            return;
        }

        Log.v("jrelog","Log starts here");''', 1)

# Turnip is a Zink/Vulkan concern. Do not export the Turnip-load request into the
# MobileGlues path just because the physical GPU is Adreno.
old_turnip = '''        if(info.isAdreno() && !PREF_ZINK_PREFER_SYSTEM_DRIVER) {
            envMap.put("POJAV_LOAD_TURNIP", "1");
        }'''
req(old_turnip in j, 'Turnip environment marker missing')
j = j.replace(old_turnip, '''        if(info.isAdreno() && LOCAL_RENDERER != null
                && LOCAL_RENDERER.toLowerCase(Locale.ROOT).contains("zink")
                && !PREF_ZINK_PREFER_SYSTEM_DRIVER) {
            envMap.put("POJAV_LOAD_TURNIP", "1");
        }''', 1)
jre.write_text(j, encoding='utf-8')


# ---------------------------------------------------------------------------
# 4) Display/frame pacing. Upstream asks for the maximum alternative refresh
# rate and starts at a 120 Hz floor. Bestiary targets a stable 60 Hz surface;
# Minecraft also receives maxFps=60 only on a brand-new options file.
# ---------------------------------------------------------------------------
surface = JAVA / 'MinecraftGLSurface.java'
m = surface.read_text(encoding='utf-8')
old_refresh = '''        // Ensures we run at correct refresh rate (should also NOT change the resolution being used)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            float maxHz = 120f; // Set to 120 by default just to be safe
            for (float altHz : getDisplay().getMode().getAlternativeRefreshRates()) {
                maxHz = Math.max(maxHz, altHz);
            }
            surface.setFrameRate(maxHz, Surface.FRAME_RATE_COMPATIBILITY_DEFAULT, Surface.CHANGE_FRAME_RATE_ONLY_IF_SEAMLESS);
        }'''
req(old_refresh in m, 'upstream max-refresh block missing')
m = m.replace(old_refresh, '''        // Stable frame pacing beats forcing a 90/120/144 Hz display while a
        // low-end phone renders Minecraft/Cobblemon at 30-60 FPS.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            float targetHz = BestiaryPerformanceProfile.targetRefreshRate();
            try {
                surface.setFrameRate(targetHz, Surface.FRAME_RATE_COMPATIBILITY_DEFAULT,
                        Surface.CHANGE_FRAME_RATE_ONLY_IF_SEAMLESS);
                Log.i("BestiaryPerformance", "Requested game surface refresh=" + targetHz + "Hz");
            } catch (Throwable t) {
                Log.w("BestiaryPerformance", "Unable to request target refresh rate", t);
            }
        }''', 1)
surface.write_text(m, encoding='utf-8')


game_defaults_java = r'''package net.kdt.pojavlaunch;

import android.content.SharedPreferences;
import android.util.Log;

import net.kdt.pojavlaunch.prefs.LauncherPreferences;
import net.kdt.pojavlaunch.utils.MCOptionUtils;

import java.io.File;

/** Conservative Minecraft 1.21.x defaults, installed only for a new options.txt. */
public final class BestiaryGamePerformanceDefaults {
    private static final String TAG = "BestiaryGameDefaults";
    private static final String REVISION_KEY = "bestiary_mc_defaults_revision";
    private static final int REVISION = 1;

    private BestiaryGamePerformanceDefaults() {}

    public static boolean shouldInstall(String gameDirPath) {
        SharedPreferences prefs = LauncherPreferences.DEFAULT_PREF;
        if (prefs != null && prefs.getInt(REVISION_KEY, 0) >= REVISION) return false;
        File options = new File(gameDirPath, "options.txt");
        return !options.isFile() || options.length() == 0;
    }

    public static void installIfFresh(boolean freshOptions) {
        if (!freshOptions) return;
        SharedPreferences prefs = LauncherPreferences.DEFAULT_PREF;
        if (prefs != null && prefs.getInt(REVISION_KEY, 0) >= REVISION) return;

        // Values follow the numeric/string serialization used by modern
        // Minecraft options.txt. Existing player settings are never overwritten.
        MCOptionUtils.set("renderDistance", "6");
        MCOptionUtils.set("simulationDistance", "5");
        MCOptionUtils.set("entityDistanceScaling", "0.5");
        MCOptionUtils.set("maxFps", "60");
        MCOptionUtils.set("enableVsync", "false");
        MCOptionUtils.set("graphicsMode", "0");
        MCOptionUtils.set("particles", "1");
        MCOptionUtils.set("ao", "false");
        MCOptionUtils.set("biomeBlendRadius", "0");
        MCOptionUtils.set("mipmapLevels", "2");
        MCOptionUtils.set("entityShadows", "false");
        MCOptionUtils.set("prioritizeChunkUpdates", "0");
        MCOptionUtils.save();

        if (prefs != null) prefs.edit().putInt(REVISION_KEY, REVISION).apply();
        Log.i(TAG, "Installed low-end first-run Minecraft defaults");
    }
}
'''
(JAVA / 'BestiaryGamePerformanceDefaults.java').write_text(game_defaults_java, encoding='utf-8')

main = JAVA / 'MainActivity.java'
ma = main.read_text(encoding='utf-8')
old_options = '''        String gameDirPath = Tools.getGameDirPath(minecraftProfile).getAbsolutePath();
        MCOptionUtils.load(gameDirPath);'''
req(old_options in ma, 'MainActivity options load marker missing')
ma = ma.replace(old_options, '''        String gameDirPath = Tools.getGameDirPath(minecraftProfile).getAbsolutePath();
        boolean installBestiaryDefaults = BestiaryGamePerformanceDefaults.shouldInstall(gameDirPath);
        MCOptionUtils.load(gameDirPath);
        BestiaryGamePerformanceDefaults.installIfFresh(installBestiaryDefaults);''', 1)
old_warning = '''        if (hasMods("sodium"))
            Logger.appendToLog("WARNING: Sodium is being used, Amethyst-Android does NOT support this mod, you are on your own");'''
req(old_warning in ma, 'upstream Sodium warning marker missing')
ma = ma.replace(old_warning, '''        if (hasMods("sodium"))
            Logger.appendToLog("Bestiary: Sodium detected; renderer-specific compatibility policy is active");''', 1)
main.write_text(ma, encoding='utf-8')


# ---------------------------------------------------------------------------
# 5) Renderer policy. AUTO remains a pinned MobileGlues baseline, but never
# overwrites a valid renderer the user already chose in the normal launcher UI.
# Explicit Bestiary overrides accept every renderer shipped by this Amethyst pin.
# ---------------------------------------------------------------------------
renderer_java = r'''package net.kdt.pojavlaunch;

import android.util.Log;

import net.kdt.pojavlaunch.prefs.LauncherPreferences;
import net.kdt.pojavlaunch.value.launcherprofiles.LauncherProfiles;
import net.kdt.pojavlaunch.value.launcherprofiles.MinecraftProfile;

public final class BestiaryRendererPolicy {
    private static final String TAG = "BestiaryRenderer";
    private static final String PREF = "bestiary_renderer";
    private static final String MOBILEGLUES = "opengles_mobileglues";

    private BestiaryRendererPolicy() {}

    public static void apply() {
        LauncherProfiles.load();
        String key = LauncherPreferences.DEFAULT_PREF.getString(LauncherPreferences.PREF_KEY_CURRENT_PROFILE, null);
        if (key == null) return;
        MinecraftProfile profile = LauncherProfiles.mainProfileJson.profiles.get(key);
        if (profile == null || !"Bestiary Rebirth".equals(profile.name)) return;

        String override = LauncherPreferences.DEFAULT_PREF.getString(PREF, "AUTO");
        String renderer = chooseRenderer(override, profile.pojavRendererName);
        if (!renderer.equals(profile.pojavRendererName)) {
            profile.pojavRendererName = renderer;
            LauncherProfiles.write();
        }
        Log.i(TAG, "renderer=" + renderer + " mode=" + override
                + " sodium=" + Tools.hasMods("sodium") + " iris=" + Tools.hasMods("iris"));
    }

    private static String chooseRenderer(String override, String existing) {
        String requested = override == null ? "AUTO" : override.trim();
        if (!"AUTO".equalsIgnoreCase(requested) && isKnownRenderer(requested)) return requested;
        // A non-MobileGlues value in the Minecraft profile is treated as a user
        // choice made through Amethyst's normal renderer UI and is preserved.
        if (isKnownRenderer(existing)) return existing;
        return MOBILEGLUES;
    }

    private static boolean isKnownRenderer(String renderer) {
        if (renderer == null) return false;
        switch (renderer) {
            case "opengles_mobileglues":
            case "opengles3_ltw":
            case "opengles2":
            case "opengles2_5":
            case "opengles3":
            case "vulkan_zink":
            case "opengles3_desktopgl_zink_kopper":
                return true;
            default:
                return false;
        }
    }
}
'''
(JAVA / 'BestiaryRendererPolicy.java').write_text(renderer_java, encoding='utf-8')


# ---------------------------------------------------------------------------
# 6) Sodium. Bestiary intentionally ships Sodium. Amethyst's generic force-run
# mitigation disables chunk rendering; restore it on MobileGlues while retaining
# the buffer-builder intrinsic guard. Other backends keep upstream mitigation.
# ---------------------------------------------------------------------------
tools = JAVA / 'Tools.java'
t = tools.read_text(encoding='utf-8')
start = '        // We only ever reach this point when user has already used the force run switch\n        boolean hasSodiumMod = false;\n'
start_at = t.find(start)
req(start_at >= 0, 'upstream Sodium mitigation start missing')
end_marker = '        // We use a janky lwjgl setup. We don\'t want more people complaining it crashes.\n'
end_at = t.find(end_marker, start_at)
req(end_at > start_at, 'upstream Sodium mitigation end missing')
sodium_replacement = r'''        boolean hasSodiumMod = hasMods(sodiumMods);
        if (hasSodiumMod) {
            boolean bestiaryMobileGlues = "opengles_mobileglues".equals(Tools.LOCAL_RENDERER);
            for (String modName : sodiumMods) {
                if (!hasMods(modName)) continue;
                File mixinPropertiesConfigFile = new File(getGameDir(), "config/" + modName + "-mixins.properties");
                List<String> lines = null;
                try {
                    lines = org.apache.commons.io.FileUtils.readLines(mixinPropertiesConfigFile, "UTF-8");
                } catch (IOException ignored) {}
                if (lines == null) lines = new ArrayList<>();

                String intrinsicGuard = "mixin.features.buffer_builder.intrinsics=false";
                if (!lines.contains(intrinsicGuard)) lines.add(intrinsicGuard);

                String chunkDisable = "mixin.features.chunk_rendering=false";
                if (bestiaryMobileGlues) {
                    while (lines.remove(chunkDisable)) {}
                } else if (!lines.contains(chunkDisable)) {
                    lines.add(chunkDisable);
                }

                try {
                    org.apache.commons.io.FileUtils.writeLines(mixinPropertiesConfigFile, lines);
                } catch (IOException ignored) {}
                Log.i("BestiarySodium", "renderer=" + Tools.LOCAL_RENDERER
                        + " mod=" + modName + " fullChunkRendering=" + bestiaryMobileGlues);
            }
        }
'''
t = t[:start_at] + sodium_replacement + t[end_at:]
tools.write_text(t, encoding='utf-8')


# ---------------------------------------------------------------------------
# 7) Bootstrap/startup I/O. Reuse one manifest per sync, allow an offline cached
# manifest, skip Mojang/Fabric network fetches when pinned local metadata is sane,
# and avoid re-hashing every unchanged managed JAR on every launcher start.
# ---------------------------------------------------------------------------
bootstrap = JAVA / 'BestiaryBootstrap.java'
b = bootstrap.read_text(encoding='utf-8')
field_marker = '    private static volatile int serverPort = 25565;\n'
req(field_marker in b, 'Bestiary runtime metadata field marker missing')
if 'runtimeManifest' not in b:
    b = b.replace(field_marker, field_marker + '    private static volatile JsonObject runtimeManifest = null;\n', 1)

# Local vanilla metadata is authoritative enough to avoid fetching Mojang's
# version manifest every launcher startup. MinecraftDownloader still verifies
# client/libraries/assets as needed.
vanilla_pattern = re.compile(
    r'    private static void ensureVanillaVersionMetadata\(\) throws Exception \{.*?\n    \}\n\n',
    re.S,
)
match = vanilla_pattern.search(b)
req(match is not None, 'ensureVanillaVersionMetadata method missing')
vanilla_method = '''    private static void ensureVanillaVersionMetadata() throws Exception {
        File dir = new File(Tools.DIR_HOME_VERSION, minecraftVersion);
        File file = new File(dir, minecraftVersion + ".json");
        if (file.isFile()) {
            try {
                JsonObject cached = JsonParser.parseString(readFile(file)).getAsJsonObject();
                if (cached.has("id") && minecraftVersion.equals(cached.get("id").getAsString())) {
                    Log.i(TAG, "Using cached Minecraft metadata " + minecraftVersion);
                    return;
                }
            } catch (Throwable ignored) {}
        }

        JsonObject root = JsonParser.parseString(readUrl(MOJANG_VERSION_MANIFEST)).getAsJsonObject();
        JsonArray versions = root.getAsJsonArray("versions");
        if (versions == null) throw new IOException("Mojang version manifest không có versions");
        JsonObject selected = null;
        for (JsonElement element : versions) {
            if (!element.isJsonObject()) continue;
            JsonObject candidate = element.getAsJsonObject();
            if (candidate.has("id") && minecraftVersion.equals(candidate.get("id").getAsString())) {
                selected = candidate;
                break;
            }
        }
        if (selected == null) throw new IOException("Không tìm thấy Minecraft " + minecraftVersion + " trong Mojang manifest");
        String source = selected.get("url").getAsString();
        String expectedSha1 = selected.has("sha1") ? selected.get("sha1").getAsString().toLowerCase(Locale.ROOT) : "";
        byte[] metadata = readUrlBytes(source);
        if (!expectedSha1.isEmpty() && !expectedSha1.equals(sha1(metadata))) {
            throw new IOException("SHA-1 metadata Minecraft " + minecraftVersion + " không khớp");
        }
        if (!dir.exists() && !dir.mkdirs()) throw new IOException("Không tạo được thư mục Minecraft " + minecraftVersion);
        writeAtomic(file, metadata);
    }

'''
b = b[:match.start()] + vanilla_method + b[match.end():]

# Cache distribution manifest once per launcher sync and persist the last valid
# Android manifest for offline launch/sync checks.
load_pattern = re.compile(
    r'    private static void loadRuntimeMetadata\(\) throws Exception \{.*?\n    \}\n\n    public static void appendQuickPlayArgs',
    re.S,
)
match = load_pattern.search(b)
req(match is not None, 'loadRuntimeMetadata method missing')
load_and_cache = '''    private static JsonObject getRuntimeManifest() throws Exception {
        JsonObject inMemory = runtimeManifest;
        if (inMemory != null) return inMemory;

        File cache = new File(Tools.DIR_GAME_HOME, "bestiary-android-manifest-cache.json");
        Exception networkFailure = null;
        try {
            JsonObject channel;
            try { channel = JsonParser.parseString(readUrl(STABLE)).getAsJsonObject(); }
            catch (Exception ignored) { channel = JsonParser.parseString(readUrl(TESTING)).getAsJsonObject(); }
            String manifestUrl = channel.has("manifestUrl")
                    ? channel.get("manifestUrl").getAsString()
                    : channel.get("manifest").getAsString();
            String raw = readUrl(manifestUrl);
            JsonObject manifest = JsonParser.parseString(raw).getAsJsonObject();
            JsonObject profiles = manifest.getAsJsonObject("profiles");
            if (profiles == null || !profiles.has("android")) {
                throw new IOException("Manifest không khai báo profile android");
            }
            runtimeManifest = manifest;
            try {
                writeAtomic(cache, raw.getBytes(StandardCharsets.UTF_8));
            } catch (Exception cacheError) {
                Log.w(TAG, "Could not persist manifest cache", cacheError);
            }
            return manifest;
        } catch (Exception e) {
            networkFailure = e;
        }

        if (cache.isFile()) {
            try {
                JsonObject manifest = JsonParser.parseString(readFile(cache)).getAsJsonObject();
                JsonObject profiles = manifest.getAsJsonObject("profiles");
                if (profiles != null && profiles.has("android")) {
                    runtimeManifest = manifest;
                    Log.w(TAG, "Network manifest unavailable; using last verified Android manifest cache");
                    return manifest;
                }
            } catch (Throwable cacheError) {
                Log.w(TAG, "Manifest cache invalid", cacheError);
            }
        }
        throw networkFailure == null ? new IOException("Không tải được manifest Android") : networkFailure;
    }

    private static void loadRuntimeMetadata() throws Exception {
        try {
            JsonObject config = JsonParser.parseString(readUrl(CONFIG)).getAsJsonObject();
            minecraftVersion = string(config, "minecraftVersion", minecraftVersion);
            fabricLoaderVersion = string(config, "defaultFabricLoader", fabricLoaderVersion);
            javaMajor = integer(config, "javaMajor", javaMajor);
            serverHost = string(config, "serverHost", serverHost);
            serverPort = integer(config, "serverPort", serverPort);
        } catch (Exception ignored) {}

        JsonObject manifest = getRuntimeManifest();
        if (manifest.has("minecraft") && manifest.get("minecraft").isJsonObject()) {
            JsonObject runtime = manifest.getAsJsonObject("minecraft");
            String loader = string(runtime, "loader", "fabric");
            if (!"fabric".equalsIgnoreCase(loader)) throw new IOException("Bestiary Android chỉ hỗ trợ Fabric: " + loader);
            minecraftVersion = string(runtime, "version", minecraftVersion);
            fabricLoaderVersion = string(runtime, "loaderVersion", fabricLoaderVersion);
            javaMajor = integer(runtime, "javaMajor", javaMajor);
        }
    }

    public static void appendQuickPlayArgs'''
b = b[:match.start()] + load_and_cache + b[match.end():]

fabric_pattern = re.compile(
    r'    private static void ensureFabricProfile\(\) throws Exception \{.*?\n    \}\n\n',
    re.S,
)
match = fabric_pattern.search(b)
req(match is not None, 'ensureFabricProfile method missing')
fabric_method = '''    private static void ensureFabricProfile() throws Exception {
        String expectedId = "fabric-loader-" + fabricLoaderVersion + "-" + minecraftVersion;
        File dir = new File(Tools.DIR_HOME_VERSION, expectedId);
        File file = new File(dir, expectedId + ".json");
        if (file.isFile()) {
            try {
                JsonObject cached = JsonParser.parseString(readFile(file)).getAsJsonObject();
                String id = cached.has("id") ? cached.get("id").getAsString() : "";
                String parent = cached.has("inheritsFrom") ? cached.get("inheritsFrom").getAsString() : "";
                if (expectedId.equals(id) && minecraftVersion.equals(parent)) {
                    Log.i(TAG, "Using cached Fabric profile " + expectedId);
                    return;
                }
            } catch (Throwable ignored) {}
        }

        String json = readUrl(fabricProfileUrl());
        JsonObject profile = JsonParser.parseString(json).getAsJsonObject();
        String id = profile.get("id").getAsString();
        if (!expectedId.equals(id)) throw new IOException("Fabric profile ID không khớp: " + id);
        dir = new File(Tools.DIR_HOME_VERSION, id);
        file = new File(dir, id + ".json");
        if (!dir.exists() && !dir.mkdirs()) throw new IOException("Không tạo được thư mục Fabric");
        writeAtomic(file, json.getBytes(StandardCharsets.UTF_8));
    }

'''
b = b[:match.start()] + fabric_method + b[match.end():]

profile_pattern = re.compile(
    r'    private static void ensureBestiaryProfile\(\) throws Exception \{.*?\n    \}\n\n    private static void syncManagedFiles',
    re.S,
)
match = profile_pattern.search(b)
req(match is not None, 'ensureBestiaryProfile method missing')
bestiary_profile_method = '''    private static void ensureBestiaryProfile() throws Exception {
        String versionId = "fabric-loader-" + fabricLoaderVersion + "-" + minecraftVersion;
        File metadata = new File(new File(Tools.DIR_HOME_VERSION, versionId), versionId + ".json");
        if (!metadata.isFile()) throw new IOException("Thiếu Fabric profile " + versionId);

        LauncherProfiles.load();
        String found = null;
        for (String key : LauncherProfiles.mainProfileJson.profiles.keySet()) {
            MinecraftProfile p = LauncherProfiles.mainProfileJson.profiles.get(key);
            if (p != null && "Bestiary Rebirth".equals(p.name)) { found = key; break; }
        }
        if (found == null) {
            found = UUID.randomUUID().toString();
            LauncherProfiles.mainProfileJson.profiles.put(found, new MinecraftProfile());
        }
        MinecraftProfile p = LauncherProfiles.mainProfileJson.profiles.get(found);
        p.name = "Bestiary Rebirth";
        p.lastVersionId = versionId;
        p.icon = "fabric";
        if (p.pojavRendererName == null || p.pojavRendererName.isBlank()) {
            p.pojavRendererName = "opengles_mobileglues";
        }
        LauncherProfiles.write();
        LauncherPreferences.DEFAULT_PREF.edit()
                .putString(LauncherPreferences.PREF_KEY_CURRENT_PROFILE, found)
                .apply();
    }

    private static void syncManagedFiles'''
b = b[:match.start()] + bestiary_profile_method + b[match.end():]

sync_pattern = re.compile(
    r'    private static void syncManagedFiles\(\) throws Exception \{.*?\n    \}\n\n    private static boolean includesAndroidProfile',
    re.S,
)
match = sync_pattern.search(b)
req(match is not None, 'syncManagedFiles method missing')
sync_method = '''    private static void syncManagedFiles() throws Exception {
        File game = new File(Tools.DIR_GAME_NEW);
        if (!game.exists() && !game.mkdirs()) throw new IOException("Không tạo được thư mục game");
        File state = new File(Tools.DIR_GAME_HOME, "bestiary-managed.json");
        Set<String> oldOwned = readOwnership(state);
        JsonObject oldVerified = readVerifiedState(state);
        JsonObject newVerified = new JsonObject();
        Set<String> desired = new HashSet<>();

        JsonObject manifest = getRuntimeManifest();
        JsonObject profileTable = manifest.getAsJsonObject("profiles");
        if (profileTable == null || !profileTable.has("android") || !profileTable.get("android").isJsonObject()) {
            throw new IOException("Manifest không khai báo profile android; không được fallback sang Full");
        }
        JsonObject androidProfile = profileTable.getAsJsonObject("android");
        JsonArray files = manifest.getAsJsonArray("files");
        if (files == null) throw new IOException("Manifest không có files");

        List<JsonObject> selected = new ArrayList<>();
        long selectedBytes = 0L;
        for (JsonElement element : files) {
            if (!element.isJsonObject()) continue;
            JsonObject item = element.getAsJsonObject();
            if (!includesAndroidProfile(item)) continue;
            selected.add(item);
            if (item.has("size")) selectedBytes += item.get("size").getAsLong();
        }

        int declaredCount = androidProfile.has("fileCount") ? androidProfile.get("fileCount").getAsInt() : -1;
        long declaredBytes = androidProfile.has("totalBytes") ? androidProfile.get("totalBytes").getAsLong() : -1L;
        if (declaredCount >= 0 && declaredCount != selected.size()) {
            throw new IOException("Android manifest lệch fileCount: khai báo " + declaredCount + ", lọc được " + selected.size());
        }
        if (declaredBytes >= 0 && declaredBytes != selectedBytes) {
            throw new IOException("Android manifest lệch totalBytes: khai báo " + declaredBytes + ", lọc được " + selectedBytes);
        }
        if (selected.isEmpty()) throw new IOException("Profile android không có file nào");

        int cacheHits = 0;
        int hashed = 0;
        int downloaded = 0;
        int completed = 0;
        for (JsonObject item : selected) {
            String relative = normalize(item.get("path").getAsString());
            if (!isAllowed(relative)) {
                completed++;
                continue;
            }
            String expected = item.get("hash").getAsString().toLowerCase(Locale.ROOT);
            String url = item.has("downloadUrl") ? item.get("downloadUrl").getAsString() : item.get("url").getAsString();
            desired.add(relative);
            File target = safeResolve(game, relative);

            int progress = 15 + (int) ((completed * 76L) / selected.size());
            setBootstrapProgress(progress, "Android " + (completed + 1) + "/" + selected.size() + ": " + target.getName());

            boolean valid = matchesVerificationCache(target, relative, expected, oldVerified);
            if (valid) {
                cacheHits++;
            } else if (target.isFile()) {
                hashed++;
                valid = expected.equals(sha256(target));
            }
            if (!valid) {
                if (target.getParentFile() != null && !target.getParentFile().exists() && !target.getParentFile().mkdirs()) {
                    throw new IOException("Không tạo được thư mục " + relative);
                }
                downloadVerified(url, target, expected);
                downloaded++;
            }
            newVerified.add(relative, verificationRecord(target, expected));
            completed++;
        }

        for (String relative : oldOwned) {
            if (desired.contains(relative)) continue;
            File target = safeResolve(game, relative);
            if (target.isFile() && !target.delete()) Log.w(TAG, "Could not remove stale managed file: " + relative);
        }
        writeManagedState(state, desired, newVerified);
        Log.i(TAG, "Android sync files=" + selected.size() + " cacheHits=" + cacheHits
                + " hashed=" + hashed + " downloaded=" + downloaded);
        setBootstrapProgress(92, "Đã đồng bộ " + selected.size() + " file của profile Android");
    }

    private static JsonObject readVerifiedState(File state) {
        if (!state.isFile()) return new JsonObject();
        try {
            JsonObject obj = JsonParser.parseString(readFile(state)).getAsJsonObject();
            JsonObject verified = obj.getAsJsonObject("verified");
            return verified == null ? new JsonObject() : verified;
        } catch (Throwable ignored) {
            return new JsonObject();
        }
    }

    private static boolean matchesVerificationCache(File file, String relative, String expected, JsonObject cache) {
        if (!file.isFile() || cache == null || !cache.has(relative) || !cache.get(relative).isJsonObject()) return false;
        try {
            JsonObject meta = cache.getAsJsonObject(relative);
            return expected.equalsIgnoreCase(meta.get("hash").getAsString())
                    && file.length() == meta.get("size").getAsLong()
                    && file.lastModified() == meta.get("mtime").getAsLong();
        } catch (Throwable ignored) {
            return false;
        }
    }

    private static JsonObject verificationRecord(File file, String hash) {
        JsonObject meta = new JsonObject();
        meta.addProperty("hash", hash.toLowerCase(Locale.ROOT));
        meta.addProperty("size", file.length());
        meta.addProperty("mtime", file.lastModified());
        return meta;
    }

    private static void writeManagedState(File state, Set<String> paths, JsonObject verified) throws Exception {
        JsonObject obj = new JsonObject();
        obj.addProperty("profile", "android");
        JsonArray arr = new JsonArray();
        paths.stream().sorted().forEach(arr::add);
        obj.add("paths", arr);
        obj.add("verified", verified);
        writeAtomic(state, Tools.GLOBAL_GSON.toJson(obj).getBytes(StandardCharsets.UTF_8));
    }

    private static boolean includesAndroidProfile'''
b = b[:match.start()] + sync_method + b[match.end():]
bootstrap.write_text(b, encoding='utf-8')


# Keep network provenance aligned with this build.
for name in ('BestiaryBootstrap.java', 'BestiaryAppUpdater.java'):
    path = JAVA / name
    if path.is_file():
        text = path.read_text(encoding='utf-8')
        text = re.sub(r'BestiaryLauncher-Android/1\.0\.\d+', 'BestiaryLauncher-Android/1.0.6', text)
        path.write_text(text, encoding='utf-8')


# ---------------------------------------------------------------------------
# Pre-build contract checks. These are intentionally extensive because this is
# the only performance patch in the final chain and should fail before Gradle.
# ---------------------------------------------------------------------------
req('versionName "1.0.6"' in build.read_text(encoding='utf-8'), '1.0.6 version missing')
req('return "";' in (JAVA / 'BestiaryJvmFlagGenerator.java').read_text(encoding='utf-8'), 'Java 21 defaults missing')
profile_text = (JAVA / 'BestiaryPerformanceProfile.java').read_text(encoding='utf-8')
req('REVISION = 6' in profile_text, 'performance revision 6 missing')
req('initialHeapMb' in profile_text, 'split Xms/Xmx policy missing')
req('targetRefreshRate' in profile_text, 'refresh-rate policy missing')
req('mg_renderer_computeShaderext", false' in profile_text, 'MobileGlues compute safe default missing')
req('BestiaryPerformanceProfile.install(this)' in app.read_text(encoding='utf-8'), 'performance startup hook missing')
req('Khôi phục JVM mặc định' in pref_java.read_text(encoding='utf-8'), 'JVM reset UI missing')
req('JVM MẶC ĐỊNH JAVA 21' in java_fragment.read_text(encoding='utf-8'), 'JVM reset handler missing')

jre_text = jre.read_text(encoding='utf-8')
req('Bestiary memory policy: Xms=' in jre_text, 'runtime split heap policy missing')
req('PREF_RAM_ALLOCATION + "M");\n        userArgs.add("-Xmx" + LauncherPreferences.PREF_RAM_ALLOCATION' not in jre_text, 'Xms=Xmx regression remains')
req('userArgs.add("-XX:ActiveProcessorCount="' not in jre_text, 'forced ActiveProcessorCount remains')
req('Continuous native logcat mirror disabled' in jre_text, 'native log gate missing')
req('LOCAL_RENDERER.toLowerCase(Locale.ROOT).contains("zink")' in jre_text, 'Turnip renderer scoping missing')

surface_text = surface.read_text(encoding='utf-8')
req('BestiaryPerformanceProfile.targetRefreshRate()' in surface_text, '60Hz surface policy missing')
req('float maxHz = 120f' not in surface_text, 'upstream 120Hz floor remains')
main_text = main.read_text(encoding='utf-8')
req('BestiaryGamePerformanceDefaults.installIfFresh' in main_text, 'Minecraft first-run defaults hook missing')
req('Amethyst-Android does NOT support this mod' not in main_text, 'obsolete Sodium warning remains')

renderer_text = (JAVA / 'BestiaryRendererPolicy.java').read_text(encoding='utf-8')
req('isKnownRenderer(existing)' in renderer_text, 'user renderer preservation missing')
req('opengles3_ltw' in renderer_text and 'vulkan_zink' in renderer_text, 'renderer override whitelist incomplete')
tools_text = tools.read_text(encoding='utf-8')
req('fullChunkRendering=' in tools_text, 'Sodium renderer policy missing')
req('mixin.features.buffer_builder.intrinsics=false' in tools_text, 'Sodium intrinsic guard missing')
req('while (lines.remove(chunkDisable)) {}' in tools_text, 'stale Sodium chunk-disable migration missing')

bootstrap_text = bootstrap.read_text(encoding='utf-8')
req('bestiary-android-manifest-cache.json' in bootstrap_text, 'manifest cache missing')
req('matchesVerificationCache' in bootstrap_text, 'managed-file verification cache missing')
req('Using cached Minecraft metadata' in bootstrap_text, 'Minecraft metadata fast path missing')
req('Using cached Fabric profile' in bootstrap_text, 'Fabric profile fast path missing')
req('readUrl(fabricProfileUrl())' in bootstrap_text, 'Fabric recovery download path missing')
req('readUrl(fabricProfileUrl())).getAsJsonObject()' not in bootstrap_text, 'Bestiary profile still re-fetches Fabric metadata')
req('android:defaultValue="0"' in pref_renderer.read_text(encoding='utf-8'), 'MobileGlues direct GLES UI default missing')
print('Bestiary Android 1.0.6 complete consolidated low-end optimization patch applied')
